nodeLinker: node-modules

packageExtensions:
  fxa-pairing-channel@*:
    dependencies:
      webpack: ^4.43.0
  react-document-title@*:
    dependencies:
      react: ^17.0.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-relock.js
    spec: "@yarnpkg/plugin-relock"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
